[fmt]
sort_imports = true
single_line_statement_blocks = "single"

[profile.default]
src = 'contracts'
test = 'test'
optimizer = true
optimizer_runs = 100_000
remappings = ["forge-std/=lib/forge-std/src/", "interfaces/=lib/interfaces/"]

[profile.ethereum]
solc_version = "0.8.25"

[profile.zksync]
solc_version = "0.8.24"
