[fmt]
sort_imports = true

[profile.default]
src = 'contracts'
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 100_000
remappings = [
  "forge-std/=lib/forge-std/src/",
  "interfaces/=lib/interfaces/contracts/",
]
